### ISSUE TITLE
Create a new user and set a password

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#100]
**Test shall include:**

1. Open window  user and create a new user: set first & last name (e.g. "First" & "Last")
2. Set System User='Y'
=> Login field becomes mandatory
3. Set a Login value (e.g. "FirstLast")
4. Call action "Change my Password"
=> action is available, modal opens
5. Set a password:
* leave old password empty
* set "demo1234" in new password
* set "demo1234" once more in new password (retype)
* OK
6. Expectations:
* new user is created, as System User
* password is set

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db 
    - (https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/195/testReport/(root)/)
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)

All Flags are ticked? Congratulations, you have delivered!

**Comment by siemiatj** [comment]
this needs an API endpoint to allow creating new users

**Comment by metas-ts** [comment]
was moved to integration_defunct on june-1st, so get the master-branch green
