### ISSUE TITLE
Set a role for a new user and check Login

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#101]
**Test shall include:**
needs #100 
 
1. open window User, select a newly created user (e.g. "FirstLast" from #100, or create one), check the Login and PW value
2. open tab Roles, and add role: WebUI
=> role WebUI is usually pre-set when adding a new role
3. Logout of the WebuI altogether
4. set Login and PW of the user you selected / created, Enter
=> Login with role: WebUI

**Comment by metas-ts** [comment]
`login_spec.js` and `user_spec.js` were moved to integration_defunct on june-1st, to get the master-branch green
