### ISSUE TITLE
Create command for selecting a date from calendar icon

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#104]
Pls create a command to select a date in calendar icon: 
=> e.g. when adding a new packing item for a product, you have to set the date for Valid from. in the calendar icon, Today is preselected. would be great to use this feature with cypress (e.g. use the preselected Today, or even Today + 2 day, - 1 week etc.; not sure how complicated that is though)

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/107

All Flags are ticked? Congratulations, you have delivered!

**Comment by siemiatj** [comment]
Some tests are failing (https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/180/testReport/(root)/
), but the new ones passed:
https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/180/testReport/(root)/Set%20product's%20CU-TU%20allocation/
