### ISSUE TITLE
Create new Parzelle / Allotment

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#109]
**Test shall include:**

- Customer Fixtures to use: (if needed)

- What to test:
1. Open window Parzelle (Allotment) (window/540210)
2. Create a new entry "Industriestrasse"

- Expectation for the test to be successful
=> new entry can be created

http://recordit.co/Udo839CfKH

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
- [x] get it integrated into `master`
  * [ ] (pull request URL)

All Flags are ticked? Congratulations, you have delivered!

**Comment by siemiatj** [comment]
Tests https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/199/testReport/(root)/

**Comment by metas-dh** [comment]
checked in mf15: **OK**
