### ISSUE TITLE
Create a manual payment

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#111]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
1. Have a sales invoice (in the video i already had one, u can create one with the sales_order_to_invoice_spec test)
2. Create a manual payment, as shown in the video (set the bpartner from invoice, doctype: Zahlungseingang, select the invoice), complete
3. Check referenced documents
4. Check the invoice

- Expectation for the test to be successful
1. invoice of the bpartner can be selected
2. after selecting the invoice, the currency and the amt are updated accordingly
3. accounting transactions are created
4. sales invoice is now marked as paid

http://recordit.co/m8WPy75DC5

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
     - https://dev544.metasfresh.com
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
    - https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/231/console
    - Screenshot: https://github.com/metasfresh/metasfresh-e2e/issues/111#issuecomment-506153316
    
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/118

All Flags are ticked? Congratulations, you have delivered!

# extra todo
- ~[ ] Create fixture for Sales Invoice.~
    q: can a fixture contain another fixture? (eg the `sales invoice` fixture should use the `simple customer` fixture).
    IMO (@TheBestPessimist) there is no fixture possible for sales invoice, as all the data in there depends on the current test being executed/developed.

**Comment by TheBestPessimist** [comment]
![image](https://user-images.githubusercontent.com/4482210/60204566-c79c5980-9857-11e9-96e6-8a46ad227556.png)
