### ISSUE TITLE
Open Handling Unit Editor

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#125]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/tBTUVWq46X

**Note:**
on customer db this window will probably take a while to open bc of data volume, pls keep this in mind when creating the test (possible time out etc.)

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/201 (2019-07-09 - ts)

All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
Check performance / data volume on customer db.

**Comment by cristinastefan90** [comment]
https://dashboard.cypress.io/#/projects/5yp4q1/runs/277/specs
