### ISSUE TITLE
Change text dunning document

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#131]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/sEOTFN0pGp

**Note:**
Dunning type and dunning document must exist, see #128, #130 

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
     * https://dashboard.cypress.io/#/projects/5yp4q1/runs/471/specs
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/294

All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
The test is partially implemented as for the moment(8/8/2019) we cannot verify text inside pdf reports using cypress.
