### ISSUE TITLE
Create credit memo for sales invoice

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#133]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/4dDTiR5179

**Note:**
you need a sales invoice for the test, fixture for that will be created by TheBestPessimist.

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
    - https://github.com/metasfresh/metasfresh-e2e/issues/133#issuecomment-506603843
    - https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/249/console
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-webui-api/pull/1220
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/180 (2019-06-28 - ts)

All Flags are ticked? Congratulations, you have delivered!

## Related issues

- https://github.com/metasfresh/metasfresh-webui-api/issues/1219

## Preconditions

A completed Sales Invoice is available but not yet paid.

**Comment by TheBestPessimist** [comment]
# Printscreen of successful run

![image](https://user-images.githubusercontent.com/4482210/60318847-36bf9e00-997d-11e9-96f4-3a5b54e2796f.png)
