### ISSUE TITLE
Sales order to shipment to invoice

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#137]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/3EY0l63RCV

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/157 (2019-06-26 - ts)
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/179 (2019-06-28 - ts)
  * [x]  https://github.com/metasfresh/metasfresh-e2e/pull/204
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/206 (2019-07-10 - ts)
    - https://github.com/metasfresh/metasfresh-e2e/pull/206#pullrequestreview-260041966

All Flags are ticked? Congratulations, you have delivered!

**Comment by metas-ts** [comment]
`sales/sales_order_to_shipment_to_invoice.js` was moved to `integration_defunct` on june-1st, to get the master-branch green

**Comment by cristinastefan90** [comment]
The test result on cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/292/specs
