### ISSUE TITLE
Change shipment date and date ready in shipment schedule

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#152]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/WrQRlaMGt2

**Note:**
1. if you change the date, not the time, only the date shall be updated (in the video, the time changes as well, to 12:00 AM, which is a bug, see https://github.com/metasfresh/metasfresh-webui-api/issues/1162
2. if you change both date and time, then ofc those shall both be updated correctly

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/186 (2019-07-02 - ts)

All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
Test results here:
https://dashboard.cypress.io/#/projects/5yp4q1/runs/239/specs
and here
https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/330/console

![image](https://user-images.githubusercontent.com/50820854/60533163-99ab8f00-9d07-11e9-8807-21a74eca6800.png)
