### ISSUE TITLE
Purchase order to material receipt to invoice

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#161]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/M0xtiHtuBD

**Note:**
1. i did not use randomly created packing items / payment terms, pls use the existing fixtures for those
2. the LU packing item was not invoiced in the video bc no price for that was on the pricelist, which is ok

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
  - The entire test suite has passed using dev591.metasfresh.com https://dashboard.cypress.io/#/projects/5yp4q1/runs/324/specs
  - https://github.com/metasfresh/metasfresh-e2e/issues/161#issuecomment-510763351
  - Tests results on cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/319/specs using dev592.metasfresh.com
  - Tests results on second ran on cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/320/specs using dev592.metasfresh.com
  - Cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/321/specs - the tests ran using dev591.metasfresh.com
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/205
    - https://github.com/metasfresh/metasfresh-e2e/pull/205#pullrequestreview-261796363

All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
Test result: https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/410/console

![image](https://user-images.githubusercontent.com/50820854/61106760-c5a4de00-a486-11e9-8fd9-6ca79266113d.png)

Cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/317/specs

**Comment by cristinastefan90** [comment]
Tests results on cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/319/specs using dev592.metasfresh.com

Tests results on second ran on cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/320/specs using dev592.metasfresh.com

Cypress board: https://dashboard.cypress.io/#/projects/5yp4q1/runs/321/specs - the tests ran using dev591.metasfresh.com
