### ISSUE TITLE
[low prio] Check z-index of modals and other views

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh-e2e#184]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [ ] run your test in jenkins e2e on a vanilla db
- [ ] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
- [ ] get it integrated into `master`
  * [ ] (pull request URL)

All Flags are ticked? Congratulations, you have delivered!

# Test concept

An e2e test which checks which views (by view i mean: modals, navbar, overlays, notifications, the referenced documents, the action menu, etc.) are over (above) and under (below) other views.

We should somehow define some rules about the z-index of each of these views, and test that via cypress.

For example the modal of a process is under the navigation bar currently, which is wrong: https://github.com/metasfresh/me03/issues/1990#issuecomment-506684448

--- 

Example:

In the Sales invoice window (http://localhost:3000/window/167/1000000), when opening a process (eg. `Gutschrift erstellen`), the modal is below the navbar.

![image](https://user-images.githubusercontent.com/4482210/60335792-64b9d800-99a7-11e9-98ae-8a49e3ac4584.png)

Navbar z-index: 100
![image](https://user-images.githubusercontent.com/4482210/60336440-068df480-99a9-11e9-98a3-d975cd94f6ed.png)

Modal z-index: 98
![image](https://user-images.githubusercontent.com/4482210/60336486-24f3f000-99a9-11e9-9d7d-8306d22e579f.png)

**Comment by siemiatj** [comment]
This won't work if `z-index' is not in inline style. And in 99% of the time it'll be a pain to add. I don't see a reason for such a test tbh. Just setting the z-indexes to values that make sens is enough.
