### ISSUE TITLE
Create material receipt with quality issue

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#210]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test:
This is about creating a material receipt where a certain % of the product qty has issues, i.e. the quality is not as good as expected (e.g. spiders in the bananas). You need:
1. a quality note (we have a fixture for that)
2. a warehouse (we have a fixture for that): the warehouse needs to be 
* Quality Issue Warehouse:Y
* Routing (= Lagerzuordnung) for Material Receipt
- Expectation for the test to be successful:
1. quality percent and quality note can be set in material receipt candidate
2. material receipt is created with:
* material receipt line with correct qty **without** quality note / quality issue percent
* material receipt line with correct qty **with** quality note / quality issue percent as set in material receipt candidates
https://recordit.co/St7FCShtXr

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
- [x] jenkins console URL / cypress dashboard URL to the successful test *suite* run (not just yours)
     - URL for the regex used in writeIntoLookupListField and writeIntoTextField
     * https://dashboard.cypress.io/#/projects/5yp4q1/runs/361/specs
     - URL for the cypress board results using dev605.metasfresh.com instance and the last changes after 'is quality issue warehouse' filter was added:
      * https://dashboard.cypress.io/#/projects/5yp4q1/runs/371/specs
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/217
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/221
  * [x]  https://github.com/metasfresh/metasfresh-e2e/pull/225

All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
If the Quality Issue Warehouse is not on the front page in Warehouse list page, then it cannot be deselected and created a new one and the tests fails. We need more investigation over this.

**Comment by cristinastefan90** [comment]
The tests results for latest PR: using dev613.metasfresh.com

https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/509/console
https://dashboard.cypress.io/#/projects/5yp4q1/runs/406/specs
