### ISSUE TITLE
Create Test: set packing item in product window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#26]
Test for adding a packing item in product window (product already existing, packing item already existing).

**Comment by metas-ts** [comment]
works on https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/240/consoleFull 👍

![image](https://user-images.githubusercontent.com/1264789/60266879-4097c180-98e9-11e9-8e0d-2caa86b6301c.png)
