### ISSUE TITLE
Open Picking Terminal and filter for Date, Product and BPartner

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#291]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

https://recordit.co/GJrWmHiAqi

**Note:**
1. i created 2 sales orders for this video, but there were already a few existing ones from running the test specs earlier (which is more realistic)
2. in a customer db there might be more than 1 picking line matching the filter params, pls keep that in mind!
3. i realized after creating the task that the menu language was set to en_US, but it had not updated, so the video shows menu language de_DE; pls let me know if this is confusing then i'll recreate the video in en_US

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- ~~[ ] run your test in jenkins e2e on a vanilla db~~
    - N/A
- ~~[ ] jenkins console URL / cypress dashboard URL to the successful test *suite* run (not just yours)~~
   - N/A
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/311

All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
The test is done but is failing due to https://github.com/metasfresh/me03/issues/2381. After this issue will be fixed, the test will pass. It will need to be moved from integration/defunct dir.

**Comment by cristinastefan90** [comment]
Also, we need to monitor this test when it will be executed on customer side as it might encounter performance issues.
