### ISSUE TITLE
Create material receipt with quality issue and invoice with unchecking In Dispute

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#347]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

2nd part for creating the invoice:
https://recordit.co/ejz3EjQYh7

1st part for creating the material receipt:
https://recordit.co/u7oV4X46LG

**Note:**
1. i used the testcase created for #345; it's basically the same test, but this time you invoice also the candidate where the material receipt had quality issues, by unchecking the In Dispute checkbox
2. invoice shall correctly display the qty / % that had quality issues

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
     * dev669.metasfresh.com
- [x] jenkins console URL / cypress dashboard URL to the successful test *suite* run (not just yours)
     * https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/711/console
     * https://dashboard.cypress.io/#/projects/5yp4q1/runs/596/specs
     * https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/715/console
     * https://dashboard.cypress.io/#/projects/5yp4q1/runs/601/specs
- [x] get it integrated into `master`
    - [x] https://github.com/metasfresh/metasfresh-e2e/pull/355

All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
The price/change_product_prices_and_add_a_new_one.js test result on jenkins:
https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/707/console
