### ISSUE TITLE
Decide on best practice in creating metasfresh testing DSL

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-e2e#5]
Currently we have a few builders to create e.g. business partners or refund contracts via cypress.
As of creating this issue, they are here: https://github.com/metasfresh/metasfresh-webui-frontend/tree/5.93/cypress/support/utils

They were inspired by https://medium.com/@axelhadfeg/builder-pattern-using-javascript-and-es6-ec1539182e24 and first introduced into metasfresh in this PR: https://github.com/metasfresh/metasfresh-webui-frontend/pull/2123

Goal of this task: research and figure out if this is a good patter to use going forward, or if there is a better way of creating a userfriendly DSL to write easily understandable cypress tests.

**Comment by siemiatj** [comment]
Ok, so this is ugly, completely unintuitive and looks like Java to me. But I guess the motivation behind using something like this is for Java devs to be able figure out what's going on. If it's gonna be easier for them to work with, then I'm ok with sticking to that. But we have to change the formatting to be in-line with the rest of our js code.

**Comment by metas-ts** [comment]
hi @siemiatj, thx for the feedback

> But I guess the motivation behind using something like this is for Java devs to be able figure out what's going on

Actually no. The motivation is to come up with a way to write a metasfresh-cypress DSL to allow (also) non-dev QA experts to write tests using metasfresh concepts such as BPartner, Product etc.
I'm confident that also our java-devs will be able to follow the pattern and extend it *even* if it's proper js ;-).

As written, i got the idea at https://medium.com/@axelhadfeg/builder-pattern-using-javascript-and-es6-ec1539182e24 (we need to stick to it more closely?)
Meanwhile I also saw this article (but didn't read it so far): https://www.dofactory.com/javascript/builder-design-pattern

So wdyt? Can you rewrite one of the existing builders to be proper js? I'm fine with dropping the builder pattern altogether if you know some better approach. 
But keep in mind that e.g. when talking about Products, there are potentially *a lot* of properties, and for 80% of them the test-author doesn't care when writing a particular test..ofc the set of properties contained in those 80% is very different between individual tests.

> But we have to change the formatting to be in-line with the rest of our js code.

Sure, np. Are the formatting rules somewhere in `.eslintrc`? Can we automatically apply them to the code, e.g. via cmdline?
I would then research and document how to make sure in the IDE that we adhere to them going forward.

**Comment by siemiatj** [comment]
I'll add the required libs and settings to the tests branch.  As for the pattern itself, I think that this implementation forces js to do things it was not designed to. This simplified implementation looks nicer at first sight, will try rewriting one class and then we can compare both.

**Comment by siemiatj** [comment]
Rewritten `DiscountSchema` to normal js class and tbh I can't see any advantage of having this Builder pattern in place. But maybe I'm missing something or I'm biased doing too much js for too long ;)

**Comment by metas-ts** [comment]
> Rewritten `DiscountSchema` to normal js class and tbh I can't see any advantage of having this Builder pattern in place. But maybe I'm missing something or I'm biased doing too much js for too long ;)

hm, i think, with that builder thing, i was biased from java..there we wanted write-only builders and read-only (immutable) pojos.
but in this case..yeah, i think the extra "builder layer" doesn't pull its weight.

**Comment by siemiatj** [comment]
So I've implemented a simple PageObject for the sales orders list:

https://github.com/metasfresh/metasfresh-e2e/pull/11/files#diff-a9f72f5ca9e133477c11567c95565a82

I've used this pattern before with selenium tests and it worked quite well. it does abstract most of the DOM querying away from tests, and since our html/styles don't change that often I think it should be good and stable enough for our case.
Cypress suggests a different approach, but with the current app architecture it's unfortunately a no go for us (https://www.cypress.io/blog/2019/01/03/stop-using-page-objects-and-start-using-app-actions/).

One thing that would be cool to have is to be able to create objets via the API without doing it in the UI. In many cases going through this process is exactly what we want, but I can imagine a lot of scenarios where it would work better already having them in place.

**Comment by metas-ts** [comment]
> One thing that would be cool to have is to be able to create objets via the API without doing it in the UI. In many cases going through this process is exactly what we want, but I can imagine a lot of scenarios where it would work better already having them in place.

@siemiatj agree. currently we have case-2-case REST-EPs, e.g. to create sales order candidates. But sooner or later i guess we will feel the need to generally post stuff into metasfresh in a generic fashion, because it will turn out that an e2e just runs too long if we add it all via UI
