### ISSUE TITLE
Fix bpartner object: location

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#57]
This issue is related to
* https://github.com/metasfresh/me03/issues/1570

=> adding a location in bpartner object is not working: 

* either field "city" is not found 
* or the country is not set: it gets selected but it looks like it does not get patched

when running i get

```
CypressError: Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'writeIntoLookupListField-1556265910609'. No request ever occurred.
```

**Comment by metas-ts** [comment]
> or the country is not set: it gets selected but it looks like it does not get patched

@metas-dh @siemiatj i believe this part is fixed in master. Remains the https://github.com/metasfresh/metasfresh-webui-frontend/issues/2251 issue

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

ran cypress test with creating 2 bpartners, using the bpartner object:
* address panel was opened correctly: OK
* location was created correctly: OK
