### ISSUE TITLE
Setup and document IDE for cypress test developers

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-e2e#6]
Note
* very probably it's going to be VS Code
* list plugins and how to install them
* document how to enable Intellisense (or link to the documentation)
* go over the "cypress" part of https://github.com/metasfresh/metasfresh-webui-frontend/blob/master/README.md, see if things can be simplified
* probably have a workshop with everyone to get them started

**Comment by siemiatj** [comment]
VSCode Plugins:
- intellisense with javascript support (maybe there's a separate plugin for cypress)
