### ISSUE TITLE
Create new bpartner group

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#70]
This issue is related to
* (e.g. a metasfresh-issue)
* (e.g. a customer issue)

**Test shall include:**
1. Have a bpartner as customer (use customer specific fixtures)
2. create new bpartner group
3. add bpartner (customer) to the group: 
* group can be selected in bpartner window
* group shows bpartner in assigned partners
4. add accounts: ??

**Fixture to be used**

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [ ] make your estimation and label (`customer:...`, `est:...`, `release:...` ) this issue accordingly
- [ ] run your test in jenkins e2e 
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/103
- [ ] add the label of your developer effort in sum (`effort: ...`)

All Flags are ticked? Congratulations, you have delivered!

**Comment by metas-ts** [comment]
works: 
![image](https://user-images.githubusercontent.com/1264789/60263485-1215e880-98e1-11e9-8850-39c8f084b658.png)
