### ISSUE TITLE
Set Tax Category inactive/active

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#75]
This issue is related to
* (e.g. a metasfresh-issue)
* (e.g. a customer issue)

=> can be done together with #74 (not necessarily in the same test!)
**Test shall include:**
1. Set Tax Category inactive
2. Inactive Tax Category cannot be selected in pricelist
3. Set Tax Category active again
4. Tax Category can be selected in pricelist

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [ ] make your estimation and label (`customer:...`, `est:...`, `release:...` ) this issue accordingly
- [ ] run your test in jenkins e2e 
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/364

All Flags are ticked? Congratulations, you have delivered!

**Comment by metas-ts** [comment]
@metas-mk @metas-dh 
* it's integrated by mark and the spec succeeds
* mark please 
  * link your PR here, and also check my review in the PR
  * check out my review and clean up the code accordingly..some of the unsuded stuff can generate FUD
* clarify with daniela if there needs to be a me03-iss for this none (maybe not)
* moving it back to "indevelopment for the time being
