### ISSUE TITLE
Filter buttons not reachable if many records

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-e2e#87]
Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e 
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/102 (2019-05-20 - ts)

All Flags are ticked? Congratulations, you have delivered!

**Comment by metas-ts** [comment]
note: the test I provided works with electron, but fails with chrome

**Comment by siemiatj** [comment]
Tests in Jenkins https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/193/testReport/(root)/Filter%20for%20a%20sysconfig%20entry/

**Comment by siemiatj** [comment]
Nothing to test here.
